startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 2
services:
  - type: web
    name: Online_Downloader
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"
      - key: CHROME_BIN
        value: "/usr/bin/chromium"
      - key: CHROMEDRIVER_PATH
        value: "/usr/bin/chromedriver"
